[libdefaults]
	default_realm = LOCALDOMAIN
	kdc_timesync = 1
	ccache_type = 4
	forwardable = true
	proxiable = true
	fcc-mit-ticketflags = true
	allow_weak_crypto = false
[realms]
	LOCALDOMAIN = {
		kdc = cobra.localdomain
		admin_server = cobra.localdomain
		default_domain = localdomain
	}
[domain_realm]
	.localdomain = LOCALDOMAIN
	localdomain = LOCALDOMAIN
